<?php

namespace AppBundle\Repository;

/**
 * competenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class competenceRepository extends \Doctrine\ORM\EntityRepository
{
}
