app :
  path : /
  defaults : {_controller: AppBundle:Default:index}

presentation :
  path : /presentation
  defaults : {_controller: AppBundle:Default:presentation}

competences :
  path : /competences
  defaults : {_controller: AppBundle:Default:competences}

realisations :
  path : /realisations
  defaults : {_controller: AppBundle:Default:realisations}

blog :
  path : /blog
  defaults : {_controller: AppBundle:Default:blog}

add_user :
  path : /adduser
  defaults : {_controller: AppBundle:Default:adduser}